### PR TITLE
TBOX-293: drop python 3.6 from ci tests

### PR DESCRIPTION
**Pull request by wpmartin**
# ↪️ Pull Request

Due to python 3.6 reaching EOL have dropped this minor version from the test matrix. Also changed the publish and build release actions to now use 3.7.
NOTE: For now we are keeping the requirement as 3.6+ so as to not introduce a breaking change for existing toolbox users.

## ✔️ PR Todo

- [x] Add documentation
- [x] Add examples
- [x] Ensure you are following the practices in the [contributor guide](https://docs.google.com/document/d/1c_hhpDMhO0zN793Z_HFOz42Q4g7l1nPRVQ5pXOUsMJU/edit) and [coding_standards](https://datatamr.atlassian.net/wiki/spaces/FEKB/blog/2020/04/14/1137606830/Customer+Success+Coding+Standards)
  * [Use consistent and descriptive name conventions](https://docs.google.com/document/d/1c_hhpDMhO0zN793Z_HFOz42Q4g7l1nPRVQ5pXOUsMJU/edit#heading=h.477s36w4rds9) 
  * [Uses google-style docstrings](https://datatamr.atlassian.net/wiki/spaces/FEKB/blog/2020/04/14/1137606830/Customer+Success+Coding+Standards#Google-style-docstrings)
  * [Uses versioned API/client methods only](https://docs.google.com/document/d/1c_hhpDMhO0zN793Z_HFOz42Q4g7l1nPRVQ5pXOUsMJU/edit#heading=h.yv6df99fyrq2)
  * [Avoid global variables](https://datatamr.atlassian.net/wiki/spaces/FEKB/blog/2020/04/14/1137606830/Customer+Success+Coding+Standards#Avoid-global-variables)
  * [Avoid giant try/catch](https://datatamr.atlassian.net/wiki/spaces/FEKB/blog/2020/04/14/1137606830/Customer+Success+Coding+Standards#Avoid-giant-try-/-except)
  * [Don't use mutable default variables](https://datatamr.atlassian.net/wiki/spaces/FEKB/blog/2020/04/14/1137606830/Customer+Success+Coding+Standards#Don%E2%80%99t-use-mutable-default-arguments)
  * [Use a `main()` function in your scripts](https://datatamr.atlassian.net/wiki/spaces/FEKB/blog/2020/04/14/1137606830/Customer+Success+Coding+Standards#Use-a-%E2%80%9Cmain()%E2%80%9D--function-in-your-scripts)
- [x] Added/updated testing for this change (ensure you are testing any changes/new code!)
- [x] Update title to link to TBOX issue (i.e. start pull request title with TBOX-xx) 
- [x] Approval from first code-reviewer
- [ ] Approval from second code-reviewer (only required if a second reviewer has left comments)
- [x] Pass all checks

### CODE REVIEW

**Review by RJSanders — DISMISSED** [review]

**Comment by zbpvarun-tamr** [comment]
Looks like there's a pending status check for 3.6 that may need to be removed as well...

**Comment by wpmartin** [comment]
weird Find behaviour in pyCharm. It would not find those usages of "3.6" from the main directory unless I added the colon

**Comment by wpmartin** [comment]
Fails trying to install pandas on 3.7, with the knock-on effect of failing to install the optional dependencies, such as google and slack. Missed on the first PR as it was still building 3.6 and I'm using 3.8.
I'll install 3.7 locally and try and debug the pandas issue

**Comment by wpmartin** [comment]
3.6 dropped from the python testing matrix and pandas minimum version upped to 1.0.0

**Review by RJSanders — APPROVED** [review]
LGTM

**Pull request merged**
