### PR TITLE
TBOX-309: update deprecated node.js actions

### PR DESCRIPTION
**Pull request by wpmartin**
Also upped the pandas version as ithe older version causes issues with git tests

## ✔️ PR Todo

- [x] Ensure you are following the practices in the [contributor guide](https://docs.google.com/document/d/1c_hhpDMhO0zN793Z_HFOz42Q4g7l1nPRVQ5pXOUsMJU/edit) and [coding_standards](https://datatamr.atlassian.net/wiki/spaces/FEKB/blog/2020/04/14/1137606830/Customer+Success+Coding+Standards)
  * [Use consistent and descriptive name conventions](https://docs.google.com/document/d/1c_hhpDMhO0zN793Z_HFOz42Q4g7l1nPRVQ5pXOUsMJU/edit#heading=h.477s36w4rds9) 
  * [Uses google-style docstrings](https://datatamr.atlassian.net/wiki/spaces/FEKB/blog/2020/04/14/1137606830/Customer+Success+Coding+Standards#Google-style-docstrings)
  * [Uses versioned API/client methods only](https://docs.google.com/document/d/1c_hhpDMhO0zN793Z_HFOz42Q4g7l1nPRVQ5pXOUsMJU/edit#heading=h.yv6df99fyrq2)
  * [Avoid global variables](https://datatamr.atlassian.net/wiki/spaces/FEKB/blog/2020/04/14/1137606830/Customer+Success+Coding+Standards#Avoid-global-variables)
  * [Avoid giant try/catch](https://datatamr.atlassian.net/wiki/spaces/FEKB/blog/2020/04/14/1137606830/Customer+Success+Coding+Standards#Avoid-giant-try-/-except)
  * [Don't use mutable default variables](https://datatamr.atlassian.net/wiki/spaces/FEKB/blog/2020/04/14/1137606830/Customer+Success+Coding+Standards#Don%E2%80%99t-use-mutable-default-arguments)
  * [Use a `main()` function in your scripts](https://datatamr.atlassian.net/wiki/spaces/FEKB/blog/2020/04/14/1137606830/Customer+Success+Coding+Standards#Use-a-%E2%80%9Cmain()%E2%80%9D--function-in-your-scripts)
- [x] Added/updated testing for this change (ensure you are testing any changes/new code!)
- [x] Update title to link to TBOX issue (i.e. start pull request title with TBOX-xx) 
- [ ] Approval from first code-reviewer
- [ ] Approval from second code-reviewer (only required if a second reviewer has left comments)
- [x] Pass all checks

### CODE REVIEW

**Comment by wpmartin** [comment]
Found more deprecations for set-output. Will upgrade these too

**Comment by wpmartin** [comment]
I updated the action commands version in CI as they were raising deprecation warnings:
https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/
e.g. "actions/checkout@v2" -> "actions/checkout@v3"
This then raised deprecation warnings on "set-output": https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

I changed where we were using it in create-draft-release, create-release, and create-zip. HOWEVER, the warnings are actually coming from the updated action in CI. The minor version GIT is calling has the redundancy, so I think we can leave it as GIT's problem.

The odd issue is that the deprecation warnings are only coming from CI, when we use v2 actions in a bunch of the workflow files, e.g. publish, create-release, etc.

**Comment by wpmartin** [comment]
updated all other uses of the checkout and setup-python to v3 to match CI. I have left the other actions on their current versions as I have no warnings to tell me that they need updating.

**Review by zbpvarun-tamr — APPROVED** [review]
I can't tell for certain if you missed any. But the changes you made make sense given the documentation you provided links to! Approving.

**Pull request merged**
