### PR TITLE
TBOX-171 Upgrade to Sphinx 3.5.4

### PR DESCRIPTION
**Pull request by along528**
Resolve invoke docs issue when using docutils 0.17.1

### CODE REVIEW

**Review by skalish — APPROVED** [review]
LGTM

**Comment by keziah-tamr** [comment]
@along528 It looks like Sphinx has fixed the issue. The docs build when using sphinx 3.5.4

**Comment by along528** [comment]
> @along528 It looks like Sphinx has fixed the issue. The docs build when using sphinx 3.5.4

I've removed the requirement for docutils 0.16 and instead upgraded to Sphinx 3.5.4

**Review by keziah-tamr — APPROVED** [review]
LGTM

**Pull request merged**
