### PR TITLE
TBOX-143: Trigger the Publish to PyPI action when a release is created

### PR DESCRIPTION
**Pull request by skalish**
# ↪️ Pull Request

This PR modifies the Publish to PyPI action to be triggered when a release is published.

## ✔️ PR Todo

- [x] Update title to link to TBOX issue (i.e. start pull request title with TBOX-xx) 
- [x] Approval from first code-reviewer
- [ ] Approval from second code-reviewer (only required if a second reviewer has left comments)
- [x] Pass all checks

### CODE REVIEW

**Comment by skalish** [comment]
I believe that `types: [released]` is correct to trigger when a draft release is published and not marked as a "pre-release".

**Comment by pareantoine** [comment]
@skalish can you provide a link to documentation or article you read that pointed you in that direction?

**Comment by skalish** [comment]
> I believe that `types: [released]` is correct to trigger when a draft release is published and not marked as a "pre-release".

Source: https://docs.github.com/en/developers/webhooks-and-events/webhook-events-and-payloads#release

Still somewhat unsure here, if anyone has more insight.

**Comment by skalish** [comment]
Okay, I can confirm from experimentation on a personal repo.

This *is* triggered when:
- A release is published
- A pre-release is changed to a release
- A draft release is published  <-- this is what our workflow will involve

This *is not* triggered when:
- A draft release is created/saved/edited
- A pre-release is published

**Review by keziah-tamr — APPROVED** [review]
LGTM

**Pull request merged**
