### PR TITLE
TBOX-314 Add scheduled CI run

### PR DESCRIPTION
**Pull request by ErinCompaan**
# ↪️ Pull Request

This adds a scheduled weekly run of the Github CI actions (set to midnight Sunday currently). 

## ✔️ PR Todo

- [X] Add documentation
- [X] Add examples
- [X] Ensure you are following the practices in the [contributor guide](https://docs.google.com/document/d/1c_hhpDMhO0zN793Z_HFOz42Q4g7l1nPRVQ5pXOUsMJU/edit) and [coding_standards](https://datatamr.atlassian.net/wiki/spaces/FEKB/blog/2020/04/14/1137606830/Customer+Success+Coding+Standards)
  * [Use consistent and descriptive name conventions](https://docs.google.com/document/d/1c_hhpDMhO0zN793Z_HFOz42Q4g7l1nPRVQ5pXOUsMJU/edit#heading=h.477s36w4rds9) 
  * [Uses google-style docstrings](https://datatamr.atlassian.net/wiki/spaces/FEKB/blog/2020/04/14/1137606830/Customer+Success+Coding+Standards#Google-style-docstrings)
  * [Uses versioned API/client methods only](https://docs.google.com/document/d/1c_hhpDMhO0zN793Z_HFOz42Q4g7l1nPRVQ5pXOUsMJU/edit#heading=h.yv6df99fyrq2)
  * [Avoid global variables](https://datatamr.atlassian.net/wiki/spaces/FEKB/blog/2020/04/14/1137606830/Customer+Success+Coding+Standards#Avoid-global-variables)
  * [Avoid giant try/catch](https://datatamr.atlassian.net/wiki/spaces/FEKB/blog/2020/04/14/1137606830/Customer+Success+Coding+Standards#Avoid-giant-try-/-except)
  * [Don't use mutable default variables](https://datatamr.atlassian.net/wiki/spaces/FEKB/blog/2020/04/14/1137606830/Customer+Success+Coding+Standards#Don%E2%80%99t-use-mutable-default-arguments)
  * [Use a `main()` function in your scripts](https://datatamr.atlassian.net/wiki/spaces/FEKB/blog/2020/04/14/1137606830/Customer+Success+Coding+Standards#Use-a-%E2%80%9Cmain()%E2%80%9D--function-in-your-scripts)
- [X] Added/updated testing for this change (ensure you are testing any changes/new code!)
- [X] Update title to link to TBOX issue (i.e. start pull request title with TBOX-xx) 
- [ ] Approval from first code-reviewer
- [ ] Approval from second code-reviewer (only required if a second reviewer has left comments)
- [ ] Pass all checks

### CODE REVIEW

**Review by zbpvarun-tamr — COMMENTED** [review]
The changes themselves look good to me. But I'm asking more out of curiosity than anything else - do you know what will happen if the ci starts failing? As in, how we will be notified?

**Comment by ErinCompaan** [comment]
> The changes themselves look good to me. But I'm asking more out of curiosity than anything else - do you know what will happen if the ci starts failing? As in, how we will be notified?

I believe only I will be notified by default (as the author of the commit containing the schedule). If someone else commits a change to the schedule, they would be notified. 
I don't think there's any easy way to e.g. send notifications to all code owners when the CI fails. If that's wanted, we might be able to set up something like this, to send custom email notifications or Slack notifications: 
https://stackoverflow.com/a/67265461/18111062

**Comment by zbpvarun-tamr** [comment]
> > The changes themselves look good to me. But I'm asking more out of curiosity than anything else - do you know what will happen if the ci starts failing? As in, how we will be notified?
> 
> I believe only I will be notified by default (as the author of the commit containing the schedule). If someone else commits a change to the schedule, they would be notified. I don't think there's any easy way to e.g. send notifications to all code owners when the CI fails. If that's wanted, we might be able to set up something like this, to send custom email notifications or Slack notifications: https://stackoverflow.com/a/67265461/18111062

Could you look into that please? Given that we're trying to expand our CI, it would be a dicey situation if it was tied to individual people's accounts... Perhaps the best option would be to send notifications to either the slack channel (if that's an option) or to the codeowners identified here: https://github.com/Datatamer/tamr-toolbox/blob/develop/.github/CODEOWNERS

**Comment by ErinCompaan** [comment]
> > > The changes themselves look good to me. But I'm asking more out of curiosity than anything else - do you know what will happen if the ci starts failing? As in, how we will be notified?
> > 
> > 
> > I believe only I will be notified by default (as the author of the commit containing the schedule). If someone else commits a change to the schedule, they would be notified. I don't think there's any easy way to e.g. send notifications to all code owners when the CI fails. If that's wanted, we might be able to set up something like this, to send custom email notifications or Slack notifications: https://stackoverflow.com/a/67265461/18111062
> 
> Could you look into that please? Given that we're trying to expand our CI, it would be a dicey situation if it was tied to individual people's accounts... Perhaps the best option would be to send notifications to either the slack channel (if that's an option) or to the codeowners identified here: https://github.com/Datatamer/tamr-toolbox/blob/develop/.github/CODEOWNERS

Makes sense. Could you give me admin rights to the repo, at least temporarily? I can't add secrets right now, which would be needed for any sort of notification.

**Comment by zbpvarun-tamr** [comment]
I think you will have admin rights once I add you as a codeowner. I've put the PR up. Can merge once the tests run.

**Comment by zbpvarun-tamr** [comment]
You are now a codeowner. Can you check if you have the privileges you need?

**Comment by ErinCompaan** [comment]
> You are now a codeowner. Can you check if you have the privileges you need?

The change does not seem to have given me admin rights, unless it takes a while to propagate (no access to repo Settings yet):
Screenshot 2023-11-07 at 9 15 29 AM

**Comment by ErinCompaan** [comment]
I added a webhook in the tf here: https://github.com/Datatamer/tf-ops-github/pull/1008/files and added a notification job to the CI which should only run for the scheduled jobs.

I changed the schedule to Wednesday midnight for now. I think this will have to be merged to see whether it works since it won't trigger anything until the new job exists on the default branch. If it does not work as expected I will iterate with subsequent PRs. 

Currently it will notify for success or for failure of the scheduled CI. That can be changed later if people want only failure notifications, but want to leave it for now so we can see if the notifications come through.

**Review by zbpvarun-tamr — APPROVED** [review]
Sounds good to me! Please keep the TBox ticket open until you have confirmed the behavior / made any additional changes you would like to make.

**Pull request merged**
