### PR TITLE
TBOX-56: Allow remote Tamr restart

### PR DESCRIPTION
**Pull request by keziah-tamr**
# ↪️ Pull Request
Add functions for restarting, starting, and stopping a tamr instance. This can be run locally or on a remote system using a user provided paramiko.SSHClient()

## ✔️ PR Todo

- [x] Add documentation
- [x] Add examples
- [x] Ensure you are following the practices in the [contributor guide](https://docs.google.com/document/d/1c_hhpDMhO0zN793Z_HFOz42Q4g7l1nPRVQ5pXOUsMJU/edit) and [coding_standards](https://datatamr.atlassian.net/wiki/spaces/FEKB/blog/2020/04/14/1137606830/Customer+Success+Coding+Standards)
  * [Use consistent and descriptive name conventions](https://docs.google.com/document/d/1c_hhpDMhO0zN793Z_HFOz42Q4g7l1nPRVQ5pXOUsMJU/edit#heading=h.477s36w4rds9) 
  * [Uses google-style docstrings](https://datatamr.atlassian.net/wiki/spaces/FEKB/blog/2020/04/14/1137606830/Customer+Success+Coding+Standards#Google-style-docstrings)
  * [Uses versioned API/client methods only](https://docs.google.com/document/d/1c_hhpDMhO0zN793Z_HFOz42Q4g7l1nPRVQ5pXOUsMJU/edit#heading=h.yv6df99fyrq2)
  * [Avoid global variables](https://datatamr.atlassian.net/wiki/spaces/FEKB/blog/2020/04/14/1137606830/Customer+Success+Coding+Standards#Avoid-global-variables)
  * [Avoid giant try/catch](https://datatamr.atlassian.net/wiki/spaces/FEKB/blog/2020/04/14/1137606830/Customer+Success+Coding+Standards#Avoid-giant-try-/-except)
  * [Don't use mutable default variables](https://datatamr.atlassian.net/wiki/spaces/FEKB/blog/2020/04/14/1137606830/Customer+Success+Coding+Standards#Don%E2%80%99t-use-mutable-default-arguments)
  * [Use a `main()` function in your scripts](https://datatamr.atlassian.net/wiki/spaces/FEKB/blog/2020/04/14/1137606830/Customer+Success+Coding+Standards#Use-a-%E2%80%9Cmain()%E2%80%9D--function-in-your-scripts)
- [x] Added/updated testing for this change (ensure you are testing any changes/new code!)
- [x] Update title to link to TBOX issue (i.e. start pull request title with TBOX-xx) 
- [x] Approval from first code-reviewer
- [ ] Approval from second code-reviewer (only required if a second reviewer has left comments)
- [x] Pass all checks

### CODE REVIEW

**Comment by keziah-tamr** [comment]
One note is that I've added "paramiko" as a requirement, but it may be better as an optional dependency. Curious to hear opinions.

**Review by olivito — APPROVED** [review]
LGTM.  I think this will be especially useful for managing internal instances

**Comment by skalish** [comment]
Is it possible to pipe through the intermediate printouts into logs?  I am able to use this successfully, but the only output I see is 
```
INFO <4627340736> [2021-11-04 12:16:35,598] tamr_toolbox.sysadmin.instance <instance.py:261> Stopping Tamr software.
INFO <4627340736> [2021-11-04 12:16:43,717] tamr_toolbox.sysadmin.instance <instance.py:270> Stopping Tamr dependencies.
INFO <4627340736> [2021-11-04 12:17:31,979] tamr_toolbox.sysadmin.instance <instance.py:213> Starting Tamr dependencies.
INFO <4627340736> [2021-11-04 12:19:50,440] tamr_toolbox.sysadmin.instance <instance.py:221> Starting Tamr software.
```
It would be nice if there was a way to see all of the feedback that I'm used to when restarting Tamr.

**Comment by keziah-tamr** [comment]
@skalish Updated code to include a verbose flag that will pipe all of the output into the INFO log in real time. When verbose is false the same info is put into DEBUG. Previously this info was put into DEBUG but it wasn't written until the process was complete. Example verbose output:

```
INFO <140735495742336> [2022-02-23 08:48:10,841] tamr_toolbox.sysadmin.instance <instance.py:46> Running command [sudo su - ubuntu -c '/home/ubuntu//tamr/stop-unify.sh'] on remote machine (unknown) as user 'keziah.katz'.
INFO <140735495742336> [2022-02-23 08:48:11,926] tamr_toolbox.sysadmin.instance <instance.py:71> STDOUT: Working directory is /home/ubuntu
Stopping running processes with pid files in /home/ubuntu/tamr/pids
Stopping unify-all (pid 7505).
INFO <140735495742336> [2022-02-23 08:48:12,928] tamr_toolbox.sysadmin.instance <instance.py:71> STDOUT: .
INFO <140735495742336> [2022-02-23 08:48:13,933] tamr_toolbox.sysadmin.instance <instance.py:71> STDOUT: .
INFO <140735495742336> [2022-02-23 08:48:14,934] tamr_toolbox.sysadmin.instance <instance.py:71> STDOUT: .
INFO <140735495742336> [2022-02-23 08:48:15,935] tamr_toolbox.sysadmin.instance <instance.py:71> STDOUT: .
INFO <140735495742336> [2022-02-23 08:48:16,941] tamr_toolbox.sysadmin.instance <instance.py:71> STDOUT: .
INFO <140735495742336> [2022-02-23 08:48:17,942] tamr_toolbox.sysadmin.instance <instance.py:71> STDOUT: .
INFO <140735495742336> [2022-02-23 08:48:18,948] tamr_toolbox.sysadmin.instance <instance.py:71> STDOUT: .
INFO <140735495742336> [2022-02-23 08:48:19,953] tamr_toolbox.sysadmin.instance <instance.py:71> STDOUT: .
INFO <140735495742336> [2022-02-23 08:48:20,953] tamr_toolbox.sysadmin.instance <instance.py:71> STDOUT: .
INFO <140735495742336> [2022-02-23 08:48:21,956] tamr_toolbox.sysadmin.instance <instance.py:71> STDOUT:  force killed after 10 seconds.
INFO <140735495742336> [2022-02-23 08:48:22,960] tamr_toolbox.sysadmin.instance <instance.py:71> STDOUT: Stopping connect (pid 8189) done.
INFO <140735495742336> [2022-02-23 08:48:23,963] tamr_toolbox.sysadmin.instance <instance.py:71> STDOUT: Stopping validify (pid 8284)-- already not running.
INFO <140735495742336> [2022-02-23 08:48:24,968] tamr_toolbox.sysadmin.instance <instance.py:71> STDOUT: Stopping previewSpark (pid 7472) done.
INFO <140735495742336> [2022-02-23 08:48:25,971] tamr_toolbox.sysadmin.instance <instance.py:87> Command ended with exit code 0.
```

**Review by skalish — APPROVED** [review]
LGTM

**Pull request merged**
